apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: falco
  namespace: flux-system
spec:
  targetNamespace: falco
  force: false
  interval: 0m20s
  path: ./fluxcd/apps/falco
  prune: false
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: fluent
    namespace: fluent-bit
  sourceRef:
    kind: GitRepository
    name: flux-system
